services:
  onboarding-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: onboarding-app:latest
    container_name: onboarding-app
    ports:
      - "8082:8080"
    environment:
      - WXO_HOST_URL=${WXO_HOST_URL:-http://localhost:3000}
      - WXO_ORCHESTRATION_ID=${WXO_ORCHESTRATION_ID:-26350222-0036-49ec-a9f0-4abaec605710}
      - WXO_AGENT_ID=${WXO_AGENT_ID:-a36ce98f-9f4e-4d46-b55d-6340dac34b16}
      - WXO_DEPLOYMENT_PLATFORM=${WXO_DEPLOYMENT_PLATFORM:-}
      - WXO_CRN=${WXO_CRN:-}
      - WXO_AGENT_ENVIRONMENT_ID=${WXO_AGENT_ENVIRONMENT_ID:-}
    restart: unless-stopped
