# Application Configuration
spring.application.name=employee-onboarding-app
server.port=8080

# Actuator Configuration
management.endpoints.web.exposure.include=health,prometheus,info,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# API Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logging
logging.level.com.demo.onboarding=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error

# CORS Configuration (for React frontend)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,PATCH,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

# watsonx Orchestrate Chat Widget Configuration
wxo.host-url=http://localhost:3000
wxo.orchestration-id=906a1a1a-9de4-468d-aa65-78bd57c9677b
wxo.agent-id=aab9725b-709e-4e01-b40a-bf56e47e9625
wxo.deployment-platform=
wxo.crn=
wxo.agent-environment-id=


